name: Feature Request
description: |
  Thanks for taking the time to suggest a new feature or improvement!
title: "[Feature]: "
labels: ["feature", "enhancement"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: ex. Ratthasas Singhamnee
      name: Thanks for taking the time to fill out this bug report!
    validations:
      required: false
  - type: dropdown
    id: request-type
    attributes:
      label: Type of request?
      description: Select the type of your request.
      options:
        - New Feature
        - Improvement
      default: 0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What is the OS which you want to suggest?
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true
  - type: textarea
    id: suggestion-details
    attributes:
      label: What are the details of your suggestion?
      description: Explain what you want
      placeholder: Feature details!
    validations:
      required: true
