name: Feature Request
description: Suggest a new feature or improvement.
title: "[Feature]: "
labels: ["feature", "enhancement"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        **Contact Details**  
        What is your name?  
        *ex. Ratthasas Singhamnee*
        
        Thank you for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: ""  # Empty label to hide the default one
      placeholder: ex. Ratthasas Singhamnee
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Type of Request**  
        Select the type of your request:
  - type: dropdown
    id: request-type
    attributes:
      label: ""
      options:
        - New Feature
        - Improvement
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Operating System**  
        What is the OS which you want to suggest?
  - type: dropdown
    id: os
    attributes:
      label: ""
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Details of Suggestion**  
        Explain what you want:
  - type: textarea
    id: suggestion-details
    attributes:
      label: ""
      placeholder: Feature details!
    validations:
      required: true
