name: Feature Request
description: Suggest a new feature or improvement.
title: "[Feature]: "
labels: ["feature", "enhancement"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature or improvement!
        
  - type: markdown
    attributes:
      value: "**Contact Details**: What is your name?"
  - type: input
    id: contact
    attributes:
      label: Contact Details
      placeholder: ex. Ratthasas Singhamnee
    validations:
      required: false

  - type: markdown
    attributes:
      value: "**Type of Request**: Select the type of your request."
  - type: dropdown
    id: request-type
    attributes:
      label: Type of request?
      options:
        - New Feature
        - Improvement
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: "**Operating System**: Select the OS related to your request."
  - type: dropdown
    id: os
    attributes:
      label: What is the OS which you want to suggest?
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: markdown
    attributes:
      value: "**Details of Suggestion**: Explain what you want."
  - type: textarea
    id: suggestion-details
    attributes:
      label: What are the details of your suggestion?
      placeholder: Feature details!
    validations:
      required: true
